apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-jaeger-deployment
  namespace: ajprakash
  labels:
    app: springboot-jaeger-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootapp-otelcollector-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: springboot-jaeger-pod
    spec:
      containers:
        - name: jaeger-mongo-db
          image: mongo

        - name: jaeger-mongo-service
          image: ajprakash/jaeger-mongo-service:2.0
          args: [ "--spring.data.mongodb.database=user_db","--spring.data.mongodb.port=27017","--spring.data.mongodb.host=localhost" ]

        - name: jaeger-user-service
          image: ajprakash/jaeger-user-service:2.0
          ports:
            - containerPort: 8383
          args: [ "--db.host=localhost","--db.port=8080","--jaeger.agent.host=<daemonset_ip>", "--jaeger.agent.port=<daemonset_port>"]
      imagePullSecrets:
        - name: ajprakash-docker-secrets
